### ISSUE TITLE
Precompilar julia

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#1]
Un punto importante para la aceleración de funciones de Julia es el precompilado y la inferencia de tipos (ver https://docs.julialang.org/en/v1/manual/performance-tips/) Sugiero en los reportes de tiempo reportar el tiempo del compilado aparte del tiempo de ejecución o bien justificar por qué no se toman separado. 

Esta tesis de doctorado puede ser útil: https://github.com/JeffBezanson/phdthesis/blob/master/main.pdf

**Comment by valperez** [comment]
Tienes razón, pero investigando más Julia hace el precompilado de la mayoría de sus funciones cuando se carga el paquete y en la primera "corrida" de la función. Es un punto importante del que ya agregue una pequeña discusión en el trabajo.
