### ISSUE TITLE
Listas vacías vuelven lento

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#11]
Esto de hacer listas vacías 
https://github.com/valperez/Tesis_Julia/blob/main/Tesis%20Julia%20con%20R/Code/MD-optimality/MD_Python.py#L13

genera problemas por la alocación de memoria. Se puede inferir el tamaño del objeto desde antes y generar listas del tamaño

**Comment by RodrigoZepeda** [comment]
Julia
https://github.com/valperez/Tesis_Julia/blob/main/Tesis%20Julia%20con%20R/Code/MD-optimality/MDopt.jl#L20

**Comment by valperez** [comment]
Ok, aquí me faltó experiencia.

**Comment by valperez** [comment]
Investigué un poco más y entiendo que lo ideal sería hacer, por ejemplo
Si = [None] * n
Si[j] = xxx
donde n es el tamaño de la lista y xxx es con lo que quiero rellenar la lista. Sin embargo, cuando yo leí mi libro de introducción a Python, aprendí la función append y fue la que se me hizo más lógica para usar en mi código. No puedo hacer
Si = [None] * n
Si[j].append(xxx) 
porque entonces me quedarían n valores None en la lista. 

Creo que lo mejor es que deje el código como está y ponga la nota de que hay otra manera que posiblemente sea más rápida pero que de todas formas creo que no haría mucha diferencia en los resultados.
