### ISSUE TITLE
Lento convertir a data frame y luego usar como matriz

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#12]
Ej
https://github.com/valperez/Tesis_Julia/blob/main/Tesis%20Julia%20con%20R/Code/MD-optimality/MD_Python.py#L105

**Comment by valperez** [comment]
Si te entiendo correctamente, me estás diciendo que creo df_MD como dataframe y después lo utilizó como matriz?? Pero según yo, siempre lo estoy usando como dataframe
