### ISSUE TITLE
Escribir pythonicamente

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#2]
En Python por ejemplo las list-comprehensions y los maps suelen ser más rápidas que los fors. Sugiero cambiarlas. No es la mejor referencia pero acá hay más tips
https://towardsdatascience.com/10-ways-to-speed-up-your-python-code-e3d57630b710

Creo que además eso te libraría de varios appends. 

De igual forma recomendaría compilar el código de python.  

Creo que también vale la pena hablar en el documento de la dependencia subjetiva de la velocidad en la programadora ¿no? O sea que accidentalmente puede alguien programar el programa más lento en el software más rápido por desconocimiento de las cosas específicas.

**Comment by valperez** [comment]
Sí, uso ambos for's y list comprenhensiones. En el Censo y en MDOpt uso mucho las list comprenhensions. En las ocasiones donde dejé el for fue para intentar tener la mejor analogía entre los 3 lenguajes y que se pudiera seguir que paso en Python es el análogo en Julia y en R. 

Y de lo segundo, tienes razón. Voy a agregar una sección que hable sobre el efecto de la experiencia y conocimiento de un lenguaje al momento de programar algo.
