### ISSUE TITLE
Lógica detrás de Pandas en MD_Python?

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#3]
No entiendo la lógica para usar `pandas` en `MD_Python` parecería que sólo necesitas la estructura de matriz y pues `pandas` es mucho más lento que sólo `numpy` 

https://stackoverflow.com/a/27889133/5067372

**Comment by RodrigoZepeda** [comment]
Bueno y la pregunta del millón en realidad es por qué no usar `cython`? 
https://blog.paperspace.com/faster-numpy-array-processing-ndarray-cython/

**Comment by valperez** [comment]
Ya hablamos de esto en privado. No usé cython porque no lo conocía, muchas gracias por la referencia.
