### ISSUE TITLE
Mencionar otros criterios

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#4]
Por ahora parece que el criterio de relevancia es el tiempo pero valdría la pena mencionar otros que no se evalúan pero pueden ser importantes. Tú discutes, por ejemplo la experiencia del usuario ¡excelente! Pero faltan otras ejemplo:
+ Exactitud numérica (sabemos¿ Yo sospecho que Julia podría tener la mayor exactitud que FORTRAN)
+ Portabilidad (python se puede correr en cualquier cosa con un buscador)
+ se te ocurre otra?

**Comment by valperez** [comment]
Por el camino en el que quiero llevar mi tesis y después de leer varios blogs, decidí que agregaré 2 cosas: 
1. La curva de aprendizaje de cada lenguaje en términos de programación en sí
2. Enfatizaré más la diferencia en cantidad de recursos de apoyo y soporte 

Gracias por el input
