### ISSUE TITLE
pdf's copy-pasteables

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#5]
No hace falta poner el `julia>` al inicio del código porque el cómo corres tú las líneas no significa que alguien más las vaya a hacer así. Se recomienda que el código procures sea copy-pasteable y si hace falta especificar el lenguaje puedes ponerle un background o bien en el comentario establecer en donde ocurre. La idea es que cualquiera del pdf vea una línea y la ejecute

**Comment by valperez** [comment]
Ya hablamos de esto en privado. En el documento de PDF decidí dejarlo así por estética y para dejar clara la diferencia en el lenguaje que estoy usando. Sin embargo, siempre hago referencia a la liga donde está el código donde fácilmente pueden hacer copy-paste directo.
