### ISSUE TITLE
Justificar sklearn por encima de statsmodels

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#6]
O sea por qué medir el tiempo en `sklearn` y no `statsmodels`?

**Comment by valperez** [comment]
Cuando estaba investigando, es la forma que encontré para medir el tiempo. Investigando un poco más, encontré que hay todo un debate y artículos dedicados sobre los pros y contras justo de estos dos paquetes. Mencionaré que hay más alternativas para medir el tiempo.
