### ISSUE TITLE
Formatear código con lintr

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#7]
Hay guías de estilo para el código. Por ejemplo las de google: 
https://google.github.io/styleguide/

o la de tidyverse
https://style.tidyverse.org/

el pep-8 de python
https://peps.python.org/pep-0008/

y la guía de julia
https://docs.julialang.org/en/v1/manual/style-guide/

Además hay paquetes que te formatean automático
Adopta una y úsala.  En particular para el pdf

Ah y el pdf lugo se sale de la página y no se lee todo.

**Comment by valperez** [comment]
Gracias, ya lo corregí
