### ISSUE TITLE
¿Por qué n/2 es un entero?

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#8]
<img width="536" alt="Screen Shot 2022-08-05 at 16 14 42" src="https://user-images.githubusercontent.com/13838319/183197141-a4268fad-498c-4069-9d4b-b325bfd65a5a.png">

**Comment by RodrigoZepeda** [comment]
Mismo problema pasa en otras ocasiones

**Comment by valperez** [comment]
Lo que pasa es que en fnames leo los dataframes con los resultados y los dataframes con los tiempos que tengo de los otros lenguajes. Son como dos conjuntos de cosas que ambos tienen la misma cardinalidad. Si tengo 5 resultados de Julia, a fuerza voy a tener 5 tiempos de Julia. Entonces n = 10
