### ISSUE TITLE
Convertir as factor dentro de formula no es más lento por la lazy evaluation?

### ISSUE THREAD

**Issue by RodrigoZepeda** [valperez/Tesis_Julia#9]
Mi entendimiento de lazy evaluation en R es que el convertir `as.factor` dentro de fórmula lo hace más lento cuando loopeas a haber asignado los factores por fuera
<img width="643" alt="Screen Shot 2022-08-05 at 16 17 15" src="https://user-images.githubusercontent.com/13838319/183199818-d4a66091-1fc5-4332-8104-35b66148ce99.png">

¿Qué opinas?

**Comment by RodrigoZepeda** [comment]
Por otro lado no estaría mal checar que no tengas otros sitios donde haya lazyevaluation en el loop y te haga todo más lento no crees?

**Comment by valperez** [comment]
Ya lo platicamos por Zoom.
